# Generated by Django 5.2.9 on 2025-12-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_direction_alter_student_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='gender',
            field=models.CharField(choices=[('ERKAK', 'Erkak'), ('AYOL', 'Ayol')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
