# Generated by Django 5.2.9 on 2025-12-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_payment_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
