# Generated by Django 5.2.9 on 2025-12-20 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_payment_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rules",
            old_name="time",
            new_name="login_time",
        ),
    ]
